default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: one_point_five_travel_development

test:
  <<: *default
  database: one_point_five_travel_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
